Update README with install instructions
ukrmap/ukrmap_rails pull request #4
Opened 2017-09-04 12:41 UTC by povodok

2017-09-04 12:58 UTC, shhavel requested changes

2017-09-04 12:58 UTC, shhavel commented on README.md
> +# Ukrmap
Please add Build Satus

2017-09-04 12:58 UTC, shhavel commented on README.md
> +  Rail's version 5.0.1
Ruby and Rails version is not necessary here. Please add repo description instead. 
Also please separate it with one empty line.

2017-09-04 12:58 UTC, shhavel commented on README.md
> +1. Clone repository:
`1.` is not needed (also `2.`, `3.`).

2017-09-04 12:58 UTC, shhavel commented on db/migrate/20170222142642_create_entries.rb
> +=begin
Please remove this comment.

2017-09-04 12:58 UTC, shhavel commented on db/migrate/20170319140813_add_fulltext_search_index_on_entries.rb
>    def up
Remove this comment

2017-09-04 12:58 UTC, shhavel commented on db/schema.rb
> -  create_table "articles", force: :cascade, options: "ENGINE=InnoDB DEFAULT CHARSET=utf8" do |t|
Database structure should not change.

2017-09-04 12:58 UTC, shhavel commented on README.md
> +    $cd ukrmaps_rails
Please add correct code formatting - 4 spaces.
Also add a space after $.

Another option format code with starting ` ``sh   and ending   ``` to add code highlighting.
See https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet

2017-09-04 12:59 UTC, shhavel commented on Gemfile
> +gem 'wdm', '>= 0.1.0'
Please add this into `development` group.

2017-09-04 14:51 UTC, shhavel commented on README.md
> +$ bundle install
This can added within previous command:

```bash
$ gem install bundler --no-ri --no-rdoc
$ bundle install
```

2017-09-04 15:24 UTC, povodok commented on db/migrate/20170319140813_add_fulltext_search_index_on_entries.rb
>    def up
I removed it

2017-09-04 21:21 UTC, shhavel commented on README.md
> +$ cd ukrmaps_rails
Typo: `ukrmaps_rails` instead of `ukrmap_rails`

2017-09-04 21:21 UTC, shhavel commented on README.md
> +```
Please remove line 26 and 27

2017-09-05 12:37 UTC, mahasamatman commented
10 commits for README is too much. Learn "git squash". Force push then.

2017-09-05 12:39 UTC, mahasamatman submitted a review, later dismissed
10 commits for README is too much. Don't want to check them. Learn "git squash". Force push then.

2017-09-05 13:19 UTC, shhavel commented
@povodok Please return empty files `vendor/assets/javascripts/.keep` and `vendor/assets/stylesheets/.keep`

2017-09-05 13:57 UTC, shhavel approved these changes

2017-09-05 13:59 UTC, merged